#!/bin/sh

case $1 in
start)
	echo "starting cic"

	insmod /lib/modules/ufs9xx_cic.ko

	exit 0

	;;
stop)
	echo "stopping cic... error, cic cannot be stopped, aborting"
	;;
*)
	echo "usage: $0 [start|stop]"
	;;
esac

