#!/bin/sh

case $1 in
start)
	echo "starting cic-ufs9xx"

	insmod /lib/modules/ufs9xx_cic.ko

	exit 0

	;;
stop)
	echo "stopping cic-ufs9xx... error, cic-ufs9xx cannot be stopped, aborting"
	;;
*)
	echo "usage: $0 [start|stop]"
	;;
esac

