#!/bin/sh

case $1 in
start)
	echo "starting enigma2"

	(
		/usr/bin/enigma2
		rtv=$?
		echo "enigma2 ended <- RTV: " $rtv
		case "$rtv" in
			0) echo "0"
				echo "E2 ERROR"
				init 6;;
			1) echo "1"
				echo "SHUTDOWN"
				init 0;;
			2) echo "2"
				echo "REBOOT"
				init 6;;
			3) echo "3"
				echo "E2 RESTART"
				echo "0" > /proc/progress
				/etc/init.d/showiframe start;;
			*) echo "*"
				echo "ERROR"
				init 6;;
		esac
	) &

	exit 0

	;;
stop)
	echo "stopping enigma2"
	killall enigma2
	killall -9 enigma2
	;;
*)
	echo "usage: $0 [start|stop]"
	;;
esac

