#!/bin/sh

case $1 in
start)
	echo "starting enigma2"

	(
		until false; do
			/usr/bin/enigma2
			rtv=$?
			echo "enigma2 ended <- RTV: " $rtv
			case "$rtv" in
				0) echo "0"
					echo "E2 ERROR"
					reboot;;
				1) echo "1"
					echo "SHUTDOWN"
					fp_control -e #Todo: Will be replaced with call to halt
					break;;
				2) echo "2"
					echo "REBOOT"
					reboot;;
				3) echo "3"
					echo "E2 RESTART"
					echo "0" > /proc/progress
					/etc/init.d/showiframe start;;
				143) echo "143"
					# Terminated by kill, stop case.
					echo "E2 SIGTERM"
					break;;
				*) echo "*"
					echo "ERROR"
					reboot;;
			esac
		done
	) &

	exit 0

	;;
stop)
	echo "stopping enigma2"
	killall enigma2
	killall -9 enigma2
	;;
*)
	echo "usage: $0 [start|stop]"
	;;
esac

