#!/bin/sh

case $1 in
start)
	echo "starting frontend-multituner"

	insmod /lib/modules/frontend_platform.ko
	insmod /lib/modules/socket.ko
	insmod /lib/modules/lnbh221.ko
	insmod /lib/modules/lnb_pio.ko
	insmod /lib/modules/lnb_a8293.ko
	if [ -e /lib/modules/avl2108.ko ]; then
		insmod /lib/modules/avl2108.ko
	fi
	if [ -e /lib/modules/avl6222.ko ]; then
		insmod /lib/modules/avl6222.ko
	fi
	if [ -e /lib/modules/cx24116.ko ]; then
		insmod /lib/modules/cx24116.ko
	fi
	if [ -e /lib/modules/stv090x.ko ]; then
		insmod /lib/modules/stv090x.ko
	fi

	exit 0

	;;
stop)
	echo "stopping frontend-multituner... error, frontend-multituner cannot be stopped, aborting"
	;;
*)
	echo "usage: $0 [start|stop]"
	;;
esac

