#!/bin/sh

case $1 in
start)
	echo "starting frontend-spark"

	insmod /lib/modules/spark.ko

	exit 0

	;;
stop)
	echo "stopping frontend-spark... error, frontend-spark cannot be stopped, aborting"
	;;
*)
	echo "usage: $0 [start|stop]"
	;;
esac

