#!/bin/sh

case $1 in
start)
	echo "starting frontend-spark"
	
	if [ -e /lib/modules/spark.ko ]; then
	insmod /lib/modules/spark.ko
	fi

	if [ -e /lib/modules/spark7162.ko ]; then
	insmod /lib/modules/spark7162.ko
	fi

	exit 0

	;;
stop)
	echo "stopping frontend-spark... error, frontend-spark cannot be stopped, aborting"
	;;
*)
	echo "usage: $0 [start|stop]"
	;;
esac

