#!/bin/sh

case $1 in
start)
	echo "starting multicom4"

	insmod /lib/modules/ics.ko firmware=1:video.elf,2:audio.elf bpa2_part=LMI_IO
	insmod /lib/modules/embx.ko
	insmod /lib/modules/embxmailbox.ko mailbox0=0xb9211000:136:set2 mailbox1=0xb9212000:137:set2
	insmod /lib/modules/mme.ko
	insmod /lib/modules/mme_user.ko

	exit 0

	;;
stop)
	echo "stopping multicom4... error, multicom4 cannot be stopped, aborting"
	;;
*)
	echo "usage: $0 [start|stop]"
	;;
esac

