#!/bin/sh

case $1 in
start)
	echo "starting player2"

	insmod /lib/modules/stmdvb.ko
	insmod /lib/modules/player2.ko discardlateframe=0
	insmod /lib/modules/sth264pp.ko
	insmod /lib/modules/stmalloc.ko
	insmod /lib/modules/platform.ko
	insmod /lib/modules/silencegen.ko

	exit 0

	;;
stop)
	echo "stopping player2... error, player2 cannot be stopped, aborting"
	;;
*)
	echo "usage: $0 [start|stop]"
	;;
esac

