#!/bin/sh
#
# /etc/init.d/rcS
#

mount /proc
mount /sys

# We have to create some dev nodes on our own
rm /dev/console
rm /dev/null
rm /dev/ttyAS0
rm /dev/zero
mknod -m 644 /dev/console c 5 1
mknod -m 644 /dev/null c 1 3
mknod -m 644 /dev/ttyAS0 c 204 40
mknod -m 644 /dev/zero c 1 5

if grep -q "quiet" /proc/cmdline; then
	exec 1>/dev/null
fi

# loadkmap < /etc/boottime.kmap

# set hostname
test -e /etc/hostname && hostname -F /etc/hostname

echo "running rc.d services..."
run-parts -a start /etc/rc.d
