#! /bin/sh
#
# rdate.sh
#
# chkconfig: S 99 0
#

RDATE=ntp2.fau.de
RDATE_ALT=ntp3.fau.de

#Check network
/bin/ping -c2 $RDATE || /bin/ping -c2 $RDATE_ALT
if [ $? -eq 0 ] ; then
#Date
echo "Running rdate -s $RDATE..."
rdate -s $RDATE || (echo "Running rdate -s $RDATE_ALT..."; rdate -s $RDATE_ALT)
#Test: rdate -p  ntp1.ptb.de
echo "Send time to FP "
/usr/bin/fp_control -s `date +"%H:%M:%S %d-%m-%Y"`
#Time
#echo "Adjusting time..."
#ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime
fi
