#!/bin/sh

showiframe_logo="bootlogo.mvi"
showiframe_logodir="/etc"
showiframe_logodiralt="/boot"

case $1 in
start)
	echo "starting showiframe"

	if [ -e $showiframe_logodir/$showiframe_logo ]; then
		showiframe -p $showiframe_logodir/$showiframe_logo &
	else
		if [ -e $showiframe_logodiralt/$showiframe_logo ]; then
			showiframe -p $showiframe_logodiralt/$showiframe_logo &
		else
			echo "starting showiframe... error, no such file $showiframe_logo, aborting"
		fi
	fi

	exit 0

	;;
stop)
	echo "stopping showiframe"
	killall showiframe
	killall -9 showiframe
	;;
*)
	echo "usage: $0 [start|stop]"
	;;
esac

