#!/bin/sh

case $1 in
start)
	echo "starting stmfb"
	if [ -e /lib/modules/stmcore-display-sti7105.ko ]; then
	if [ -e /lib/modules/stmcore-display-sti7105.ko ] ;then
		insmod /lib/modules/stmcore-display-sti7105.ko
	else
		insmod /lib/modules/stmcore-display-sti7111.ko
	fi
	insmod /lib/modules/stmfb.ko display0=1280x720-32@50:15m:pal:yuv:yuv;
	insmod /lib/modules/stm_v4l2.ko
	fi
	if [ -e /lib/modules/stmcore-display-sti7111.ko ]; then
	insmod /lib/modules/stmcore-display-sti7111.ko
	insmod /lib/modules/stmfb.ko display0=1280x720-32@50:15m:pal:yuv:yuv;
	insmod /lib/modules/stm_v4l2.ko
	fi

	exit 0

	;;
stop)
	echo "stopping stmfb... error, stmfb cannot be stopped, aborting"
	;;
*)
	echo "usage: $0 [start|stop]"
	;;
esac

