obj-m       += avs.o
avs-objs	+= tools.o ak4705.o avs_core.o stv6412.o cxa2161.o \
			   fake_avs.o stv6417.o stv6418.o avs_none.o avs_pio.o \
			   vip2_avs.o vip1_avs.o


CCFLAGSY	+= -DDEBUG
EXTRA_CFLAGS += $(CCFLAGSY)

