obj-m           += cec.o
cec-objs        += cec_main.o \
                   cec_worker.o \
                   cec_opcodes.o \
                   cec_internal.o \
                   cec_proc.o \
                   cec_rc.o \
                   cec_dev.o
