#!/bin/sh

/bin/update &

/sbin/ifconfig lo 127.0.0.1
/bin/hostname $HOSTNAME

sleep 4

echo "Mount usb /dev/sda1"
mount /dev/sda1 /mnt
if [ ! -d /mnt/kathrein/ufs913 ]
then
  echo "ERROR: NO UPDATEFOLDER ON USB"
  killall -9 update
  /bin/update "ERR: NOUSB" &
  exit 0
fi

echo "Check fw"
killall -9 update
/bin/update "UPDATE FW" &
if [ -e /mnt/kathrein/ufs913/mtd_fw.sum.bin ]; then
  echo "Write fw"
  flash_eraseall -j /dev/mtd8
  nandwrite -a -m -p /dev/mtd8 /mnt/kathrein/ufs913/mtd_fw.sum.bin
  #dd of=/dev/mtdblock8 if=/mnt/kathrein/ufs913/mtd_fw.sum.bin
fi

echo "Check rootfs"
killall -9 update
/bin/update "UPDATE ROOT" &
if [ -e /mnt/kathrein/ufs913/mtd_root.sum.bin ]; then
  echo "Write rootfs"
  flash_eraseall -j /dev/mtd9
  nandwrite -a -m -p /dev/mtd9 /mnt/kathrein/ufs913/mtd_root.sum.bin
  #dd of=/dev/mtdblock9 if=/mnt/kathrein/ufs913/mtd_root.sum.bin
fi

killall -9 update
/bin/update "UPDATE UIMAGE" &
echo "Check uImage"
if [ -e /mnt/kathrein/ufs913/uImage.bin ]; then
  echo "Write uImage"
  dd if=/mnt/kathrein/ufs913/uImage.bin of=/dev/mtdblock6
fi

echo "Reboot"
reboot -f
